<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Authors>Alexey Mokrov, Rene Peuser</Authors>
    <Company></Company>
    <Description>A simple library to get an abstraction to FileInfo and DirectoryInfo. As an addition you had for each object a service which you can use for better coding and handle accessing to the IO in a better way.</Description>
    <Copyright>Copyright 2020 (c) Alexey Mokrov, Rene Peuser. All rights reserved.</Copyright>
    <PackageLicenseFile>license.txt</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/RenePeuser/FileSystem.Abstraction</PackageProjectUrl>
    <RepositoryUrl>https://github.com/RenePeuser/FileSystem.Abstraction</RepositoryUrl>
    <PackageReleaseNotes>Prerelease of FileSystem.Abstraction

Bug-Fixes / Changes
- When delete or create a folder sometimes properties like "exists" was not updated.</PackageReleaseNotes>
    <PackageTags>C#;IO;FileSystem;FileInfo;DirectoryInfo;FileSystemInfo</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\license.txt">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>